server:
  port: 8085

spring:
  application:
    name: book-my-ticket

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: ${DB_URL:jdbc:mysql://mysql-container:3306/book-my-ticket?createDatabaseIfNotExist=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:admin@123}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      url: redis://redis-container:6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: kusumacr19@gmail.com
    password: geylgfuvsnnrhwsj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

admin:
  email: admin@gmail.com
  password: admin

cloudinary:
  url: ${CLOUDINARY_URL:cloudinary://123456789012345:dummy_secret@dummy_cloud}
