apiVersion: v1
kind: Service
metadata:
  name: book-my-ticket-service
  namespace: production
spec:
  type: NodePort
  selector:
    app: book-my-ticket
  ports:
    - port: 8085
      targetPort: 8085
      nodePort: 30080