apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-my-ticket-app
  namespace: production
  labels:
    app: book-my-ticket
spec:
  replicas: 2
  selector:
    matchLabels:
      app: book-my-ticket
  template:
    metadata:
      labels:
        app: book-my-ticket
    spec:
      containers:
        - name: book-my-ticket
          image: kusumacr21/book-my-ticket:latest   # overwritten by Pipeline 2
          ports:
            - containerPort: 8085
          env:
            - name: "jdbc:mysql://mysql-service.production.svc.cluster.local:3306/book-my-ticket?createDatabaseIfNotExist=true"
              valueFrom:
                secretKeyRef: { name: app-secret, key: db-url }
            - name: "root"
              valueFrom:
                secretKeyRef: { name: app-secret, key: db-username }
            - name: "admin@123"
              valueFrom:
                secretKeyRef: { name: app-secret, key: db-password }
            - name: "redis://redis-service.production.svc.cluster.local:6379"
              valueFrom:
                secretKeyRef: { name: app-secret, key: redis-url }
            - name: "kusumacr19@gmail.com"
              valueFrom:
                secretKeyRef: { name: app-secret, key: mail-username }
            - name: "geylgfuvsnnrhwsj"
              valueFrom:
                secretKeyRef: { name: app-secret, key: mail-password }
            - name: "admin@gmail.com"
              valueFrom:
                secretKeyRef: { name: app-secret, key: admin-email }
            - name: "admin"
              valueFrom:
                secretKeyRef: { name: app-secret, key: admin-password }
            - name: "cloudinary://123456789012345:dummy_secret@dummy_cloud"
              valueFrom:
                secretKeyRef: { name: app-secret, key: cloudinary-url }
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"