apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: production
type: Opaque
stringData:
  db-url: "jdbc:mysql://mysql-service.production.svc.cluster.local:3306/book-my-ticket?createDatabaseIfNotExist=true"
  db-username: "root"
  db-password: "admin@123"
  redis-url: "redis://redis-service.production.svc.cluster.local:6379"
  mail-username: "kusumacr19@gmail.com"
  mail-password: "geylgfuvsnnrhwsj"
  admin-email: "admin@gmail.com"
  admin-password: "admin@123"
  cloudinary-url: "cloudinary://api_key:api_secret@cloud_name"